### ISSUE TITLE
[SR-6290] Bad Int values shown in Xcode variable view when viewing Dictionary with enum keys

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4502]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6290      |
   |Radar             | rdar://problem/35337096         |
   |Original Reporter | igz (JIRA User)      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Done    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164962413-ac951d0b-9888-4ad2-9b55-01f8b6850341.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @keith      |
   |Priority          | Medium      |

   

   md5: ea795ebb805bae527b2ecf72fb3ccfc7

  </details>

**Issue Description:**

Bad integer values are shown in Xcode's variable view when inspecting dictionaries with string-based enum keys. Correct values are shown when the keys are created with the enum cases' rawValues.

Contrary to what the variable view shows, the actual values do match the input.

 

<img src="image-2017-11-02-07-13-45-639.png" width="750" />

**Comment by belkadan** [comment]
@swift-ci create

**Comment by keith** [comment]
The root of this issue appears to be that the byte offsets that are calculated here <https://github.com/apple/swift-lldb/blob/stable/source/Symbol/SwiftASTContext.cpp#L501-L521> are wrong. In this repro case where we have an enum for the dictionary keys, and an int for the values, the tuple created by SwiftHashedContainer has 9 bytes, the first 1 for the enum, and the other 8 for the int. Yet the offsets calculated here are 0, and 8 instead of 0 and 1. This leads us to print this garbage data instead. I'm still not entirely sure why this only affects the dictionary case, and not just any tuple with an enum and an int (the offsets in that case are also 0 and 8, but it prints correctly), but I'm still looking into that.

**Comment by keith** [comment]
Ok so this appears to be the case because the bytes for the key of the tuple are padded in the case of defining a tuple by itself, but they're not padded in the case they're in a dictionary. This results in the expected size of the tuple type generated by lldb to be 16 bytes, yet the data given to it is only 9 bytes. It actually seems like the solution here should be padding the key, instead of getting a different offset for the type.

**Comment by keith** [comment]
I've submitted a fix for this and would love feedback on it! <https://github.com/apple/swift-lldb/pull/259>

**Comment by keith** [comment]
I'm still trying to debug the test failure that seems to be caused by my fix. In the meantime I've submitted a separate PR to add some tests around this use case. Currently this specific bug's test is disabled (until a fix is merged), but some related cases have been added. <https://github.com/apple/swift-lldb/pull/262>

**Comment by keith** [comment]
Fixed in https://github.com/apple/swift-lldb/pull/259
